version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports: 
      - 27017:27017
    volumes: 
      - yolo:/data/db
    networks:
      - yolo_network

  server:
    container_name: server
    restart: unless-stopped
    build: 
      context: ./backend
    environment: 
      - DB_HOST=mongodb
    volumes:
      - yolo:/data/db/backend
    depends_on: 
      - mongodb
    ports: 
      - 5000:5000
    stdin_open: true
    tty: true
    networks:
      - yolo_network
    
  client:
    container_name: client
    restart: unless-stopped
    build: 
      context: ./client
    volumes:
      - yolo:/data/db/client
    ports:
      - 3000:3000
    depends_on: 
      - server
    networks: 
      - yolo_network
    stdin_open: true

volumes: 
  yolo

networks:
  yolo_network:
    driver: bridge    
       

