version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports: 
      - "27017:27017"
    volumes: 
      - yolo:/data/db
    networks:
      - yolo_network

  backend:
    container_name: backend
    restart: unless-stopped
    build: 
      dockerfile: Dockerfile
      context: ./backend
    environment: 
      - DB_HOST=mongodb
    volumes:
      - ./backend:/app
    depends_on: 
      - mongodb
    image: yolo/backend:v1.0.0
    ports: 
      - "5001:5001"
    stdin_open: true
    tty: true
    networks:
      - yolo_network
    
  client:
    container_name: client
    restart: unless-stopped
    build: 
      dockerfile: Dockerfile
      context: ./client

    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    image: yolo/client:v1.0.0
    networks: 
      - yolo_network
    stdin_open: true

volumes: 
  yolo:

networks:
  yolo_network:
    driver: bridge  

       

