version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports: 
      - "27017:27017"
    volumes: 
      - yolo:/data/db
    networks:
      - yolo_network

  server:
    container_name: server
    restart: unless-stopped
    build: 
      dockerfile: Dockerfile
      context: ./backend
    environment: 
      - DB_HOST=mongodb
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app
    depends_on: 
      - mongodb
    ports: 
      - "5000:5000"
    stdin_open: true
    tty: true
    networks:
      - yolo_network
    
  client:
    container_name: client
    restart: unless-stopped
    build: 
      dockerfile: Dockerfile
      context: ./client

    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    ports:
      - "3000:3000"
    depends_on: 
      - server
    networks: 
      - yolo_network
    stdin_open: true

volumes: 
  yolo:

networks:
  yolo_network:
    driver: bridge    
       

